[tool.poetry]
name = "pysnmp-pyasn1"
version = "1.1.4-beta.2"
description = "ASN.1 types and codecs"
authors = ["rfaircloth-splunk <rfaircloth@splunk.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/pysnmp/pyasn1"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Telecommunications Industry",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Communications",
    "Topic :: Software Development :: Libraries :: Python Modules",
    # Make sure these classifiers are in your setup.py
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
]
readme = "README.md"
packages = [
    { include = "pyasn1" },
]
include = ["docs", "tests"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
Sphinx = "^4.3.0"
isort = "^6.0.1"
black = "^25.1.0"
pyflakes = "^3.3.2"
autoflake = "^2.3.1"
flake8 = "^7.2.0"
pre-commit = "^4.2.0"
mypy = "^1.15.0"

[build-system]
requires = ["setuptools>=42", "wheel", "build"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

# Configure Black formatting
[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311", "py312", "py313"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

# Configure isort to be compatible with black
[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
skip_gitignore = true
skip_glob = ["*.pyi", ".git/*", ".tox/*", ".venv/*", "build/*", "dist/*"]
