[tox]
envlist = py39, py310, py311, py312, py313, coverage, lint, pre-commit
isolated_build = True
skip_missing_interpreters = True

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
# No more unittest2 dependency
commands =
    python -m unittest discover tests

[testenv:coverage]
deps =
    coverage
commands =
    coverage run -m unittest discover tests
    coverage report -m
    coverage html
    coverage xml

[testenv:lint]
deps =
    flake8
    black
    pre-commit
commands =
    flake8 pyasn1 tests --config=.flake8
    black --check pyasn1 tests
    pre-commit run --all-files

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files

[testenv:publish]
deps =
    build
    twine
    poetry
commands =
    python -m build
    poetry config pypi-token.pypi {env:PYPI_TOKEN}
    poetry publish -n

[flake8]
config = .flake8
