[tox]
envlist = py310, py311, py312, py313, py314, coverage, lint, pre-commit
skip_missing_interpreters = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
commands =
    python -m unittest discover tests

[testenv:coverage]
deps =
    coverage
commands =
    coverage run -m unittest discover tests
    coverage report -m
    coverage html
    coverage xml

[testenv:lint]
deps =
    flake8
    black
    pre-commit
commands =
    flake8 pyasn1 tests --config=.flake8
    black --check pyasn1 tests
    pre-commit run --all-files

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files

[flake8]
config = .flake8
