[tox]
envlist = py38, py39, py310, py311, py312, py313, coverage
isolated_build = True
skip_missing_interpreters = True

[testenv]
# No more unittest2 dependency
commands =
    python -m unittest discover tests

[testenv:coverage]
deps =
    coverage
commands =
    coverage run -m unittest discover tests
    coverage report -m
    coverage html

[testenv:lint]
deps =
    flake8
    black
commands =
    flake8 pyasn1 tests --config=.flake8
    black --check pyasn1 tests

[flake8]
max-line-length = 100
exclude = .tox,*.egg,build,data
select = E,W,F
